### ISSUE TITLE
Add strikethrough when hovering over added files (data processing)

### ISSUE THREAD

**Issue by AndrewLester** [frc1418/VictiScout#110]
Add a strikethrough and "clickable" cursor when hovering over an element to show it can be removed upon clicking.

**Comment by ErikBoesen** [comment]
Might want to make a tag for issues relating to processing. Do you have the permissions to do that? I'll do it if not.

**Comment by AndrewLester** [comment]
I don't have the permissions for that.

**Comment by ErikBoesen** [comment]
Made a tag and added it to all the open issues regarding the processing system.
