### ISSUE TITLE
Occasionally outputs data with WYSIWYG-style quotes

### ISSUE THREAD

**Issue by ErikBoesen** [frc1418/VictiScout#44]
No idea why this happens.

**Comment by Twinters007** [comment]
In which category?

**Comment by ErikBoesen** [comment]
@Twinters007 It will choose one or two random quotes in the JSON and use right and left quotes: “”, as in Microsoft Word, rather than the JSON usual "". )Other times, one match will contain totally broken data.)

**Comment by Twinters007** [comment]
I wonder if it has to do with the person putting in the data. If their computer is set up weirdly?

**Comment by ErikBoesen** [comment]
@Twinters007 I initially thought it could have something to do with Aki's Japanese settings on his computer, since he was the first one to have the issue. But John also had the issue last competition, so it seems to not be related to that.

**Comment by ErikBoesen** [comment]
Doesn't matter anymore, since the quotes are being replaced. But I'd still like to find out why this happens.
