### ISSUE TITLE
Add field position selector

### ISSUE THREAD

**Issue by ErikBoesen** [frc1418/VictiScout#47]
For far blue, middle red, etc.

**Comment by Twinters007** [comment]
But why? 2017 is over

**Comment by ErikBoesen** [comment]
We can use it next year.

**Comment by Twinters007** [comment]
Yeah but it may not be as clear cut as far blue, middle red, etc

**Comment by ErikBoesen** [comment]
I will leave this up to this year's maintainers to decide how to implement this. A very simple implementation can be found in the branch `position-selector`.
