### ISSUE TITLE
Does not build binaries

### ISSUE THREAD

**Issue by Dev-Osmium** [frc1418/VictiScout#48]
Ran command `npm run-script package-win`, got error
```
Fatal error: Unable to parse version string
 undefined
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! VictiScout@2.0.0 package-win: electron-packager . --platform=win32 --arch=all --out ~/Desktop/Scout --overwrite --ignore=\.gitignore
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the VictiScout@2.0.0 package-win script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Owen Salter\AppData\Roaming\npm-cache\_logs\2017-12-01T23_30_27_652Z-debug.log
```

**Comment by ErikBoesen** [comment]
What's your build platform? Cross-compilation to Windows isn't possible with `electron-packager`.

**Comment by Dev-Osmium** [comment]
Windows 10 64 bit

**Comment by ErikBoesen** [comment]
Try changing the output directory in `package.json` to something valid for Windows.

**Comment by ErikBoesen** [comment]
Alternatively, flash Arch Linux.

**Comment by Dev-Osmium** [comment]
Thanks!

**Comment by ErikBoesen** [comment]
Did that work? (The first option :) )

**Comment by Dev-Osmium** [comment]
No, I loaded up my linux VM and built it there, then emailed the finished binaries to myself. Thanks for the help!

**Comment by ErikBoesen** [comment]
I'd like to keep this open since it remains an issue despite it working out alright for you.

**Comment by Dev-Osmium** [comment]
No problem

**Comment by ErikBoesen** [comment]
It should be fine now. Thank you for letting us know about this issue!
