### ISSUE TITLE
Create field position selector

### ISSUE THREAD

**Issue by ErikBoesen** [frc1418/VictiScout#51]
During competitions, we choose who will scout each robot based on that robot's position on the field relative to the bleachers. For example, "Furthest blue," "Middle Red," or "Closest blue."

This allows us to not have to worry about who's going to scout whom before every individual game. However, it can still become a headache as people leave the stands and new ones join. In the past, we've tried to counter this by handing out physical tokens (laminated notecards) designating each position, such that a scouter has to give their token to another person before leaving and nobody will ever forget which position they are to be scouting. These tokens, however, are easy to break, drop, and lose, and occasionally a distraction while scouting. I don't think we should abandon the idea yet, but we should experiment with a better way to handle scouting positions.

My proposal is to add an option to the VictiScout dashboard which would allow scouters to select which field position they're scouting. When selected, their position would be displayed in a prominent position such that other scouters can easily see it.

**Comment by AndrewLester** [comment]
Change to dropdown list for simplicity.

**Comment by ianzullo** [comment]
Resolved by recent pull request.
