### ISSUE TITLE
Firebase connection

### ISSUE THREAD

**Issue by Bananajojo123** [frc1418/VictiScout#66]
I was wondering if there is any way to attach the file to Firebase.

**Comment by ErikBoesen** [comment]
Given that this application is designed to operate without internet connection, no, this is not possible. It would be feasible if internet connection were routinely accessible, but during FRC competitions it is not.

**Comment by Bananajojo123** [comment]
Well, if you did have internet, is there a way for it to be possible?

**Comment by ErikBoesen** [comment]
Yes, you'd configure it just like you would any other Firebase connection.

**Comment by Bananajojo123** [comment]
ok
