### ISSUE TITLE
Remove parked checkbox?

### ISSUE THREAD

**Issue by ErikBoesen** [frc1418/VictiScout#88]
I don't think it's that relevant for us to know... thoughts?

**Comment by JosephCarpenter** [comment]
I think it is still useful, because it shows whether the team has good time management skills/can drive up a ramp (yes, I'm pretty sure there was one team I saw that couldn't even drive up the slightly slanted ramp)

**Comment by ErikBoesen** [comment]
@JosephCarpenter It's often pointless to get on the ramp, though (levitate will automatically climb a team even if they're off the ramp at game end so it's often more useful for them to continue putting cubes in the vault). And it's not really important to know this when we're analyzing data.
