### ISSUE TITLE
Think about removing Attempted options

### ISSUE THREAD

**Issue by ErikBoesen** [frc1418/VictiScout#89]
Realistically, it's not THAT important for us to know whether a robot has tried to climb. All that's important is whether they are actually capable of doing it. Attempts can be noted in the notes anyway.

**Comment by JosephCarpenter** [comment]
Yeah, the few times an attempt is worth noting it can be put in the notes. On a somewhat unrelated note, what I think would be a useful thing to have is a "didn't move" checkbox. I can't even remember how many times I had to type that in notes
